# Generated by Django 4.1.7 on 2023-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='fname')),
                ('last_name', models.CharField(max_length=50, verbose_name='lname')),
                ('user_name', models.CharField(max_length=50, verbose_name='uname')),
                ('password', models.CharField(max_length=50, verbose_name='passwrod')),
                ('password_again', models.CharField(max_length=50, verbose_name='password_again')),
            ],
        ),
    ]
